set -g mouse on
set -sg escape-time 0
set -g extended-keys always
set -g allow-passthrough on
set -s set-clipboard on
set -g focus-events on

# status bar
set -g status-bg "#282828"
set -g status-fg "#a89984"
set -g status-left ""
set -g status-right "#[fg=#83a598]#H"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set-window-option -g window-status-current-style "fg=#ebdbb2,bg=#504945"

# copy mode
set -g mode-style "bg=#504945,fg=#ebdbb2"
bind -T copy-mode-vi a send-keys -X cancel
bind -T copy-mode-vi i send-keys -X cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe
bind r run "bash $HOME/.config/tmux/reload"
bind x kill-pane # disable confirmation prompt: confirm-before -p "kill-pane #W? (y/n)" kill-pane
# splitting panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

unbind h
bind h select-pane -L
unbind l
bind l select-pane -R
unbind k
bind k select-pane -U
unbind j
bind j select-pane -D

bind H swap-window -t -1\; select-window -t -1
bind L swap-window -t +1\; select-window -t +1

# drag a window in the status bar to reorder it
bind -n MouseDrag1Status swap-window -d -t=

# merge another window into this one as a split
bind g choose-window 'join-pane -h -s "%%"'
bind G choose-window 'join-pane -v -s "%%"'

# flip orientation of the current pane against its sibling
bind f move-pane -h -t '.-'
bind F move-pane -v -t '.-'
