source ~/.config/zsh/.zshrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pnpm
export PNPM_HOME="/Users/christopherkapic/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# bun completions
[ -s "/Users/christopherkapic/.bun/_bun" ] && source "/Users/christopherkapic/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/christopherkapic/.lmstudio/bin"
# End of LM Studio CLI section
